environment:
  nodejs_version: "lts"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm ci

test_script:
  - node --version
  - npm --version
  - npm test

build: off
